spring.application.name=catalog-service
server.port=8083

spring.datasource.url=jdbc:postgresql://catalog-service-postgres:5432/catalog_service_db
# spring.datasource.url=jdbc:postgresql://localhost:9435/catalog_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# for BATCH sending (INSERT, UPDATE)
spring.jpa.properties.hibernate.jdbc.batch_size=20
# for SQL requests grouping (for 1 entity)
spring.jpa.properties.hibernate.order_inserts=true
# grouping all UPDATE for 1 entity
spring.jpa.properties.hibernate.order_updates=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.root=INFO
logging.level.com.akerugen.catalogservice=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
