version: '3'

services:
  user-service:
    image: ebookstore-microservices/user-service:0.0.1-SNAPSHOT
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "9091:8081" # Внешний порт : Внутренний порт
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-service-postgres:5432/user_service_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_SHOW_SQL=false
    depends_on:
      user-service-postgres:
        condition: service_healthy
    networks:
      - ebookstore-microservices
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-service-postgres:
    image: postgres:17
    container_name: user-service-postgres
    environment:
      - POSTGRES_DB=user_service_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "9433:5432"
    volumes:
      - user_service_postgres_data:/var/lib/postgresql/data
    networks:
      - ebookstore-microservices
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  auth-service:
    image: ebookstore-microservices/auth-service:0.0.1-SNAPSHOT
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "9092:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-service-postgres:5432/auth_service_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

      - JWT_SECRET=e7b1324642c76106e9e685101203d88c5694320b41ce3b270f989bc5069757ba
      - JWT_ACCESS_TOKEN_EXPIRATION=3600000
      - JWT_REFRESH_TOKEN_EXPIRATION=604800000

      - USER_SERVICE_URL=http://user-service:8081

      - SPRING_CACHE_TYPE=redis
      - SPRING_CACHE_REDIS_TIME_TO_LIVE=600000
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_TIMEOUT=2000ms
      - SPRING_REDIS_LETTUCE_POOL_MAX_ACTIVE=20
      - SPRING_REDIS_LETTUCE_POOL_MAX_IDLE=10
      - SPRING_REDIS_LETTUCE_POOL_MIN_IDLE=5
    depends_on:
      auth-service-postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - ebookstore-microservices
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  auth-service-postgres:
    image: postgres:17
    container_name: auth-service-postgres
    environment:
      - POSTGRES_DB=auth_service_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "9434:5432"
    volumes:
      - auth_service_postgres_data:/var/lib/postgresql
    networks:
      - ebookstore-microservices
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d auth_service_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ebookstore-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - ebookstore-microservices
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  ebookstore-microservices:
    driver: bridge

volumes:
  user_service_postgres_data:
  auth_service_postgres_data:
  redis_data:
