apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: ebookstore
type: Opaque
stringData:
  AUTH_DB_PASSWORD: "postgres"
  USER_DB_PASSWORD: "postgres"

  JWT_SECRET: "e7b1324642c76106e9e685101203d88c5694320b41ce3b270f989bc5069757ba"

  REDIS_PASSWORD: ""
