spring.application.name=user-service
server.port=8081

spring.datasource.url=jdbc:postgresql://user-service-postgres:5432/user_service_db
# spring.datasource.url=jdbc:postgresql://localhost:9433/user_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

logging.level.root=INFO
logging.level.com.akerugen.userservice=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
