apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ebookstore
data:
  # auth-service
  AUTH_DB_HOST: "auth-db"
  AUTH_DB_PORT: "5432"
  AUTH_DB_NAME: "auth_service_db"
  AUTH_DB_USER: "postgres"
  JWT_EXPIRATION: "3600000"  # 1 час в ms
  REFRESH_TOKEN_EXPIRATION: "604800000"  # 7 дней в ms

  # user-service
  USER_DB_HOST: "user-db"
  USER_DB_PORT: "5432"
  USER_DB_NAME: "user_service_db"
  USER_DB_USER: "postgres"

  # redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  # catalog-service
  CATALOG_DB_HOST: "catalog-db"
  CATALOG_DB_PORT: "5432"
  CATALOG_DB_NAME: "catalog_service_db"
  CATALOG_DB_USER: "postgres"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8084"
  USER_SERVICE_URL: "http://user-service:8081"

  # notification-service
  NOTIFICATION_DB_HOST: "notification-db"
  NOTIFICATION_DB_PORT: "5432"
  NOTIFICATION_DB_NAME: "notification_service_db"
  NOTIFICATION_DB_USER: "postgres"

  # application
  APP_ENV: "kubernetes"
  SPRING_PROFILES_ACTIVE: "prod"
